# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f55b9656a5dd42f47f4055e58d4d362853f42549167f9b23580f2949d21c8383dc0270013d55ed94f203294aa75db26b0fab10c17e38276797f1e4e513c513c7

test:
  secret_key_base: f2fee9c0a360a30acb3a0f5b120e1b59a5fa6e81b29b6c34a7acea2c3b23e2707fb88788e2425b41352808d37521f9950816096cbfd92375fde2f21f5e4aec12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
